# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/deepin/codework/ttc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/deepin/codework/ttc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deepin/codework/ttc/CMakeFiles /home/deepin/codework/ttc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deepin/codework/ttc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ttc

# Build rule for target.
ttc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ttc
.PHONY : ttc

# fast build rule for target.
ttc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/build
.PHONY : ttc/fast

#=============================================================================
# Target rules for targets named ttc_autogen_timestamp_deps

# Build rule for target.
ttc_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ttc_autogen_timestamp_deps
.PHONY : ttc_autogen_timestamp_deps

# fast build rule for target.
ttc_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc_autogen_timestamp_deps.dir/build.make CMakeFiles/ttc_autogen_timestamp_deps.dir/build
.PHONY : ttc_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ttc_autogen

# Build rule for target.
ttc_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ttc_autogen
.PHONY : ttc_autogen

# fast build rule for target.
ttc_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc_autogen.dir/build.make CMakeFiles/ttc_autogen.dir/build
.PHONY : ttc_autogen/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/core.dir/build.make src/core/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named core_autogen_timestamp_deps

# Build rule for target.
core_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_autogen_timestamp_deps
.PHONY : core_autogen_timestamp_deps

# fast build rule for target.
core_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/core_autogen_timestamp_deps.dir/build.make src/core/CMakeFiles/core_autogen_timestamp_deps.dir/build
.PHONY : core_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named core_autogen

# Build rule for target.
core_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_autogen
.PHONY : core_autogen

# fast build rule for target.
core_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/core_autogen.dir/build.make src/core/CMakeFiles/core_autogen.dir/build
.PHONY : core_autogen/fast

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/ui.dir/build.make src/ui/CMakeFiles/ui.dir/build
.PHONY : ui/fast

#=============================================================================
# Target rules for targets named ui_autogen_timestamp_deps

# Build rule for target.
ui_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_autogen_timestamp_deps
.PHONY : ui_autogen_timestamp_deps

# fast build rule for target.
ui_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/ui_autogen_timestamp_deps.dir/build.make src/ui/CMakeFiles/ui_autogen_timestamp_deps.dir/build
.PHONY : ui_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ui_autogen

# Build rule for target.
ui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_autogen
.PHONY : ui_autogen

# fast build rule for target.
ui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/ui_autogen.dir/build.make src/ui/CMakeFiles/ui_autogen.dir/build
.PHONY : ui_autogen/fast

#=============================================================================
# Target rules for targets named viewer

# Build rule for target.
viewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 viewer
.PHONY : viewer

# fast build rule for target.
viewer/fast:
	$(MAKE) $(MAKESILENT) -f src/viewer/CMakeFiles/viewer.dir/build.make src/viewer/CMakeFiles/viewer.dir/build
.PHONY : viewer/fast

#=============================================================================
# Target rules for targets named viewer_autogen_timestamp_deps

# Build rule for target.
viewer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 viewer_autogen_timestamp_deps
.PHONY : viewer_autogen_timestamp_deps

# fast build rule for target.
viewer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/viewer/CMakeFiles/viewer_autogen_timestamp_deps.dir/build.make src/viewer/CMakeFiles/viewer_autogen_timestamp_deps.dir/build
.PHONY : viewer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named viewer_autogen

# Build rule for target.
viewer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 viewer_autogen
.PHONY : viewer_autogen

# fast build rule for target.
viewer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/viewer/CMakeFiles/viewer_autogen.dir/build.make src/viewer/CMakeFiles/viewer_autogen.dir/build
.PHONY : viewer_autogen/fast

#=============================================================================
# Target rules for targets named archive

# Build rule for target.
archive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archive
.PHONY : archive

# fast build rule for target.
archive/fast:
	$(MAKE) $(MAKESILENT) -f src/archive/CMakeFiles/archive.dir/build.make src/archive/CMakeFiles/archive.dir/build
.PHONY : archive/fast

#=============================================================================
# Target rules for targets named archive_autogen_timestamp_deps

# Build rule for target.
archive_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archive_autogen_timestamp_deps
.PHONY : archive_autogen_timestamp_deps

# fast build rule for target.
archive_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/archive/CMakeFiles/archive_autogen_timestamp_deps.dir/build.make src/archive/CMakeFiles/archive_autogen_timestamp_deps.dir/build
.PHONY : archive_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named archive_autogen

# Build rule for target.
archive_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archive_autogen
.PHONY : archive_autogen

# fast build rule for target.
archive_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/archive/CMakeFiles/archive_autogen.dir/build.make src/archive/CMakeFiles/archive_autogen.dir/build
.PHONY : archive_autogen/fast

#=============================================================================
# Target rules for targets named search

# Build rule for target.
search: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 search
.PHONY : search

# fast build rule for target.
search/fast:
	$(MAKE) $(MAKESILENT) -f src/search/CMakeFiles/search.dir/build.make src/search/CMakeFiles/search.dir/build
.PHONY : search/fast

#=============================================================================
# Target rules for targets named search_autogen_timestamp_deps

# Build rule for target.
search_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 search_autogen_timestamp_deps
.PHONY : search_autogen_timestamp_deps

# fast build rule for target.
search_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/search/CMakeFiles/search_autogen_timestamp_deps.dir/build.make src/search/CMakeFiles/search_autogen_timestamp_deps.dir/build
.PHONY : search_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named search_autogen

# Build rule for target.
search_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 search_autogen
.PHONY : search_autogen

# fast build rule for target.
search_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/search/CMakeFiles/search_autogen.dir/build.make src/search/CMakeFiles/search_autogen.dir/build
.PHONY : search_autogen/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock_autogen_timestamp_deps

# Build rule for target.
gmock_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_autogen_timestamp_deps
.PHONY : gmock_autogen_timestamp_deps

# fast build rule for target.
gmock_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock_autogen_timestamp_deps.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_autogen_timestamp_deps.dir/build
.PHONY : gmock_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gmock_autogen

# Build rule for target.
gmock_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_autogen
.PHONY : gmock_autogen

# fast build rule for target.
gmock_autogen/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock_autogen.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_autogen.dir/build
.PHONY : gmock_autogen/fast

#=============================================================================
# Target rules for targets named gmock_main_autogen_timestamp_deps

# Build rule for target.
gmock_main_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main_autogen_timestamp_deps
.PHONY : gmock_main_autogen_timestamp_deps

# fast build rule for target.
gmock_main_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock_main_autogen_timestamp_deps.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main_autogen_timestamp_deps.dir/build
.PHONY : gmock_main_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gmock_main_autogen

# Build rule for target.
gmock_main_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main_autogen
.PHONY : gmock_main_autogen

# fast build rule for target.
gmock_main_autogen/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock_main_autogen.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main_autogen.dir/build
.PHONY : gmock_main_autogen/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest.dir/build.make googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest_autogen_timestamp_deps

# Build rule for target.
gtest_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_autogen_timestamp_deps
.PHONY : gtest_autogen_timestamp_deps

# fast build rule for target.
gtest_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest_autogen_timestamp_deps.dir/build.make googletest-build/googletest/CMakeFiles/gtest_autogen_timestamp_deps.dir/build
.PHONY : gtest_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gtest_autogen

# Build rule for target.
gtest_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_autogen
.PHONY : gtest_autogen

# fast build rule for target.
gtest_autogen/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest_autogen.dir/build.make googletest-build/googletest/CMakeFiles/gtest_autogen.dir/build
.PHONY : gtest_autogen/fast

#=============================================================================
# Target rules for targets named gtest_main_autogen_timestamp_deps

# Build rule for target.
gtest_main_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main_autogen_timestamp_deps
.PHONY : gtest_main_autogen_timestamp_deps

# fast build rule for target.
gtest_main_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest_main_autogen_timestamp_deps.dir/build.make googletest-build/googletest/CMakeFiles/gtest_main_autogen_timestamp_deps.dir/build
.PHONY : gtest_main_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gtest_main_autogen

# Build rule for target.
gtest_main_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main_autogen
.PHONY : gtest_main_autogen

# fast build rule for target.
gtest_main_autogen/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest_main_autogen.dir/build.make googletest-build/googletest/CMakeFiles/gtest_main_autogen.dir/build
.PHONY : gtest_main_autogen/fast

#=============================================================================
# Target rules for targets named core_tests

# Build rule for target.
core_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_tests
.PHONY : core_tests

# fast build rule for target.
core_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/core/CMakeFiles/core_tests.dir/build.make tests/core/CMakeFiles/core_tests.dir/build
.PHONY : core_tests/fast

#=============================================================================
# Target rules for targets named core_tests_autogen_timestamp_deps

# Build rule for target.
core_tests_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_tests_autogen_timestamp_deps
.PHONY : core_tests_autogen_timestamp_deps

# fast build rule for target.
core_tests_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/core/CMakeFiles/core_tests_autogen_timestamp_deps.dir/build.make tests/core/CMakeFiles/core_tests_autogen_timestamp_deps.dir/build
.PHONY : core_tests_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named core_tests_autogen

# Build rule for target.
core_tests_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_tests_autogen
.PHONY : core_tests_autogen

# fast build rule for target.
core_tests_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/core/CMakeFiles/core_tests_autogen.dir/build.make tests/core/CMakeFiles/core_tests_autogen.dir/build
.PHONY : core_tests_autogen/fast

#=============================================================================
# Target rules for targets named ui_tests

# Build rule for target.
ui_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_tests
.PHONY : ui_tests

# fast build rule for target.
ui_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/ui/CMakeFiles/ui_tests.dir/build.make tests/ui/CMakeFiles/ui_tests.dir/build
.PHONY : ui_tests/fast

#=============================================================================
# Target rules for targets named ui_tests_autogen_timestamp_deps

# Build rule for target.
ui_tests_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_tests_autogen_timestamp_deps
.PHONY : ui_tests_autogen_timestamp_deps

# fast build rule for target.
ui_tests_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/ui/CMakeFiles/ui_tests_autogen_timestamp_deps.dir/build.make tests/ui/CMakeFiles/ui_tests_autogen_timestamp_deps.dir/build
.PHONY : ui_tests_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ui_tests_autogen

# Build rule for target.
ui_tests_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_tests_autogen
.PHONY : ui_tests_autogen

# fast build rule for target.
ui_tests_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/ui/CMakeFiles/ui_tests_autogen.dir/build.make tests/ui/CMakeFiles/ui_tests_autogen.dir/build
.PHONY : ui_tests_autogen/fast

#=============================================================================
# Target rules for targets named archive_tests

# Build rule for target.
archive_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archive_tests
.PHONY : archive_tests

# fast build rule for target.
archive_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/archive/CMakeFiles/archive_tests.dir/build.make tests/archive/CMakeFiles/archive_tests.dir/build
.PHONY : archive_tests/fast

#=============================================================================
# Target rules for targets named archive_tests_autogen_timestamp_deps

# Build rule for target.
archive_tests_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archive_tests_autogen_timestamp_deps
.PHONY : archive_tests_autogen_timestamp_deps

# fast build rule for target.
archive_tests_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/archive/CMakeFiles/archive_tests_autogen_timestamp_deps.dir/build.make tests/archive/CMakeFiles/archive_tests_autogen_timestamp_deps.dir/build
.PHONY : archive_tests_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named archive_tests_autogen

# Build rule for target.
archive_tests_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 archive_tests_autogen
.PHONY : archive_tests_autogen

# fast build rule for target.
archive_tests_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/archive/CMakeFiles/archive_tests_autogen.dir/build.make tests/archive/CMakeFiles/archive_tests_autogen.dir/build
.PHONY : archive_tests_autogen/fast

#=============================================================================
# Target rules for targets named bench_dirlisting

# Build rule for target.
bench_dirlisting: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_dirlisting
.PHONY : bench_dirlisting

# fast build rule for target.
bench_dirlisting/fast:
	$(MAKE) $(MAKESILENT) -f bench/CMakeFiles/bench_dirlisting.dir/build.make bench/CMakeFiles/bench_dirlisting.dir/build
.PHONY : bench_dirlisting/fast

#=============================================================================
# Target rules for targets named bench_dirlisting_autogen_timestamp_deps

# Build rule for target.
bench_dirlisting_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_dirlisting_autogen_timestamp_deps
.PHONY : bench_dirlisting_autogen_timestamp_deps

# fast build rule for target.
bench_dirlisting_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f bench/CMakeFiles/bench_dirlisting_autogen_timestamp_deps.dir/build.make bench/CMakeFiles/bench_dirlisting_autogen_timestamp_deps.dir/build
.PHONY : bench_dirlisting_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named bench_dirlisting_autogen

# Build rule for target.
bench_dirlisting_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_dirlisting_autogen
.PHONY : bench_dirlisting_autogen

# fast build rule for target.
bench_dirlisting_autogen/fast:
	$(MAKE) $(MAKESILENT) -f bench/CMakeFiles/bench_dirlisting_autogen.dir/build.make bench/CMakeFiles/bench_dirlisting_autogen.dir/build
.PHONY : bench_dirlisting_autogen/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

ttc_autogen/3YJK5W5UP7/qrc_resources.o: ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.o
.PHONY : ttc_autogen/3YJK5W5UP7/qrc_resources.o

# target to build an object file
ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.o
.PHONY : ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.o

ttc_autogen/3YJK5W5UP7/qrc_resources.i: ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.i
.PHONY : ttc_autogen/3YJK5W5UP7/qrc_resources.i

# target to preprocess a source file
ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.i
.PHONY : ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.i

ttc_autogen/3YJK5W5UP7/qrc_resources.s: ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.s
.PHONY : ttc_autogen/3YJK5W5UP7/qrc_resources.s

# target to generate assembly for a file
ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.s
.PHONY : ttc_autogen/3YJK5W5UP7/qrc_resources.cpp.s

ttc_autogen/mocs_compilation.o: ttc_autogen/mocs_compilation.cpp.o
.PHONY : ttc_autogen/mocs_compilation.o

# target to build an object file
ttc_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/ttc_autogen/mocs_compilation.cpp.o
.PHONY : ttc_autogen/mocs_compilation.cpp.o

ttc_autogen/mocs_compilation.i: ttc_autogen/mocs_compilation.cpp.i
.PHONY : ttc_autogen/mocs_compilation.i

# target to preprocess a source file
ttc_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/ttc_autogen/mocs_compilation.cpp.i
.PHONY : ttc_autogen/mocs_compilation.cpp.i

ttc_autogen/mocs_compilation.s: ttc_autogen/mocs_compilation.cpp.s
.PHONY : ttc_autogen/mocs_compilation.s

# target to generate assembly for a file
ttc_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ttc.dir/build.make CMakeFiles/ttc.dir/ttc_autogen/mocs_compilation.cpp.s
.PHONY : ttc_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... archive_autogen"
	@echo "... archive_autogen_timestamp_deps"
	@echo "... archive_tests_autogen"
	@echo "... archive_tests_autogen_timestamp_deps"
	@echo "... bench_dirlisting_autogen"
	@echo "... bench_dirlisting_autogen_timestamp_deps"
	@echo "... core_autogen"
	@echo "... core_autogen_timestamp_deps"
	@echo "... core_tests_autogen"
	@echo "... core_tests_autogen_timestamp_deps"
	@echo "... gmock_autogen"
	@echo "... gmock_autogen_timestamp_deps"
	@echo "... gmock_main_autogen"
	@echo "... gmock_main_autogen_timestamp_deps"
	@echo "... gtest_autogen"
	@echo "... gtest_autogen_timestamp_deps"
	@echo "... gtest_main_autogen"
	@echo "... gtest_main_autogen_timestamp_deps"
	@echo "... search_autogen"
	@echo "... search_autogen_timestamp_deps"
	@echo "... ttc_autogen"
	@echo "... ttc_autogen_timestamp_deps"
	@echo "... ui_autogen"
	@echo "... ui_autogen_timestamp_deps"
	@echo "... ui_tests_autogen"
	@echo "... ui_tests_autogen_timestamp_deps"
	@echo "... viewer_autogen"
	@echo "... viewer_autogen_timestamp_deps"
	@echo "... archive"
	@echo "... archive_tests"
	@echo "... bench_dirlisting"
	@echo "... core"
	@echo "... core_tests"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... search"
	@echo "... ttc"
	@echo "... ui"
	@echo "... ui_tests"
	@echo "... viewer"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... ttc_autogen/3YJK5W5UP7/qrc_resources.o"
	@echo "... ttc_autogen/3YJK5W5UP7/qrc_resources.i"
	@echo "... ttc_autogen/3YJK5W5UP7/qrc_resources.s"
	@echo "... ttc_autogen/mocs_compilation.o"
	@echo "... ttc_autogen/mocs_compilation.i"
	@echo "... ttc_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

