option(FILECOMMANDER_ENABLE_NETWORK "Build network providers" ON)
option(FILECOMMANDER_PREVIEW_PDF "Build Poppler PDF preview" ON)
option(FILECOMMANDER_PREVIEW_MEDIA "Build media preview" ON)
option(FILECOMMANDER_PREVIEW_OFFICE "Build office-oxide integration" ON)
set(FILECOMMANDER_MEDIA_BACKEND "auto" CACHE STRING
    "Media backend: auto, mpv, windowsmf, or none")
set_property(CACHE FILECOMMANDER_MEDIA_BACKEND PROPERTY STRINGS auto mpv windowsmf none)

if(WIN32)
    option(FILECOMMANDER_ENABLE_LINUX_INTEGRATION
           "Build Linux-only DBus, GVFS, X11, libsecret and libsmbclient integration" OFF)
else()
    option(FILECOMMANDER_ENABLE_LINUX_INTEGRATION
           "Build Linux-only DBus, GVFS, X11, libsecret and libsmbclient integration" ON)
endif()

set(FILECOMMANDER_HAS_NETWORK 0)
set(FILECOMMANDER_HAS_PREVIEW_PDF 0)
set(FILECOMMANDER_HAS_PREVIEW_MEDIA 0)
set(FILECOMMANDER_HAS_PREVIEW_OFFICE 0)
set(FILECOMMANDER_HAS_LINUX_INTEGRATION 0)
set(FILECOMMANDER_MEDIA_BACKEND_MPV 0)
set(FILECOMMANDER_MEDIA_BACKEND_WINDOWSMF 0)

string(TOLOWER "${FILECOMMANDER_MEDIA_BACKEND}" _fc_media_backend)
if(NOT FILECOMMANDER_PREVIEW_MEDIA)
    set(_fc_media_backend none)
elseif(_fc_media_backend STREQUAL "auto")
    if(WIN32)
        set(_fc_media_backend windowsmf)
    else()
        set(_fc_media_backend mpv)
    endif()
endif()
if(NOT _fc_media_backend MATCHES "^(mpv|windowsmf|none)$")
    message(FATAL_ERROR
        "FILECOMMANDER_MEDIA_BACKEND must be auto, mpv, windowsmf, or none.")
endif()
if(_fc_media_backend STREQUAL "windowsmf" AND NOT WIN32)
    message(FATAL_ERROR "FILECOMMANDER_MEDIA_BACKEND=windowsmf is Windows-only.")
endif()
set(FILECOMMANDER_RESOLVED_MEDIA_BACKEND "${_fc_media_backend}" CACHE INTERNAL
    "Resolved media backend")

if(FILECOMMANDER_ENABLE_NETWORK)
    set(FILECOMMANDER_HAS_NETWORK 1)
endif()
if(FILECOMMANDER_PREVIEW_PDF)
    set(FILECOMMANDER_HAS_PREVIEW_PDF 1)
endif()
if(NOT FILECOMMANDER_RESOLVED_MEDIA_BACKEND STREQUAL "none")
    set(FILECOMMANDER_HAS_PREVIEW_MEDIA 1)
endif()
if(FILECOMMANDER_RESOLVED_MEDIA_BACKEND STREQUAL "mpv")
    set(FILECOMMANDER_MEDIA_BACKEND_MPV 1)
elseif(FILECOMMANDER_RESOLVED_MEDIA_BACKEND STREQUAL "windowsmf")
    set(FILECOMMANDER_MEDIA_BACKEND_WINDOWSMF 1)
endif()
if(FILECOMMANDER_PREVIEW_OFFICE)
    set(FILECOMMANDER_HAS_PREVIEW_OFFICE 1)
endif()
if(FILECOMMANDER_ENABLE_LINUX_INTEGRATION)
    set(FILECOMMANDER_HAS_LINUX_INTEGRATION 1)
endif()
